name: neuroscan
channels:
  - conda-forge
  - pytorch
dependencies:
  - pip
  - python
  - jupyterlab
  - cellpose
  - czifile
  - matplotlib
  - napari
  - pyqt
  - scikit-image
  - pip:
    - -r requirements.txt
    - -e .
